name: CI

on:
  push:
    branches:
      - '*'   # cualquier branch

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pytest

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

    - name: List files root
      run: ls -la

    - name: List files src
      run: ls -la src

    - name: Run tests
      working-directory: src
      run: pytest

    - name: Build Docker image
      run: docker build -t coppelchallenge:latest -f src/Dockerfile .
